const express = require('express');
const router = express.Router();
const Issue = require('../models/Issue');
const IssueUpdate = require('../models/IssueUpdate');
const IssueConfirmation = require('../models/IssueConfirmation');
const DepartmentDependency = require('../models/DepartmentDependency');
const Department = require('../models/Department');
const { requireAuth, requireRole } = require('../middleware/authMiddleware');
const upload = require('../middleware/uploadMiddleware');
const { classifyIssue, generateIssuePlan, generateProfessionalOrder } = require('../services/aiService');

// Duplicate/Cluster detection (Geo-proximity + text)
async function findDuplicateCluster(lat, lng, category) {
  // Find issues within 50 meters with the same category
  const radiusInRadian = 50 / 6378100; // 50 meters
  
  const nearby = await Issue.findOne({
    category,
    status: { $in: ['open', 'assigned', 'in_progress'] },
    location: {
      $geoWithin: {
        $centerSphere: [[lng, lat], radiusInRadian]
      }
    }
  });

  if (nearby) {
    if (!nearby.clusterId) {
      nearby.clusterId = nearby._id.toString();
      await nearby.save();
    }
    return nearby.clusterId;
  }
  return null;
}

// POST /api/issues - Create an issue
router.post('/', requireAuth, upload.single('photo'), async (req, res) => {
  try {
    const { title, description, area, lat, lng } = req.body;
    const photoUrl = req.file ? req.file.path : null;

    // AI Classification
    const aiResult = await classifyIssue(`${title} ${description}`, photoUrl);

    // Get Department ObjectIds
    let primaryDept = null;
    let linkedDepts = [];

    if (aiResult.suggestedDepartments.length > 0) {
      const depts = await Department.find({ name: { $in: aiResult.suggestedDepartments } });
      if (depts.length > 0) {
        primaryDept = depts[0]._id;
        linkedDepts = depts.slice(1).map(d => d._id);
      }
    }

    // Duplicate detection
    const clusterId = await findDuplicateCluster(parseFloat(lat), parseFloat(lng), aiResult.category);

    const newIssue = new Issue({
      title,
      description,
      category: aiResult.category,
      urgencyScore: aiResult.urgencyScore,
      photoUrl,
      location: {
        type: 'Point',
        coordinates: [parseFloat(lng), parseFloat(lat)],
      },
      area,
      primaryDepartment: primaryDept,
      linkedDepartments: linkedDepts,
      clusterId: clusterId || undefined,
      reporterId: req.user._id,
      aiSummary: aiResult.summary,
    });

    if (!clusterId) {
      newIssue.clusterId = newIssue._id.toString();
    }

    await newIssue.save();

    // Create DepartmentDependencies if overlapping
    if (primaryDept && linkedDepts.length > 0) {
      for (let linkedId of linkedDepts) {
        await DepartmentDependency.create({
          issueId: newIssue._id,
          dependentDepartment: primaryDept,
          prerequisiteDepartment: linkedId,
          notes: 'Auto-generated by AI due to cross-department overlap',
        });
      }
    }

    // Emit socket event
    const io = req.app.get('io');
    if (io) {
      io.emit('ISSUE_CREATED', newIssue);
    }

    res.status(201).json(newIssue);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/issues/nearby - Get issues by bounding box or center
router.get('/nearby', async (req, res) => {
  try {
    const { lat, lng, maxDistance = 5000 } = req.query; // maxDistance in meters

    let query = {};
    if (lat && lng) {
      query.location = {
        $near: {
          $geometry: {
            type: 'Point',
            coordinates: [parseFloat(lng), parseFloat(lat)],
          },
          $maxDistance: parseInt(maxDistance),
        },
      };
    }

    const issues = await Issue.find(query)
      .populate('primaryDepartment', 'name')
      .populate('linkedDepartments', 'name')
      .sort({ createdAt: -1 })
      .limit(200);
      
    res.json(issues);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /api/issues/:id/status - Department updates status
router.patch('/:id/status', requireAuth, requireRole(['officer', 'dept_admin', 'admin', 'super_admin']), async (req, res) => {
  try {
    const { status, comment } = req.body;
    const issue = await Issue.findById(req.params.id);
    
    if (!issue) return res.status(404).json({ error: 'Issue not found' });

    const previousStatus = issue.status;
    issue.status = status;
    await issue.save();

    const update = await IssueUpdate.create({
      issueId: issue._id,
      updatedBy: req.user._id,
      departmentId: req.user.department,
      previousStatus,
      newStatus: status,
      comment,
    });

    // Resolve dependencies if status is resolved
    if (status === 'resolved') {
      await DepartmentDependency.updateMany(
        { issueId: issue._id, prerequisiteDepartment: req.user.department },
        { status: 'unblocked' }
      );
    }

    const io = req.app.get('io');
    if (io) io.emit('ISSUE_UPDATED', { issueId: issue._id, status, update });

    res.json(issue);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /api/issues/:id/reassign - Manual reassignment
router.patch('/:id/reassign', requireAuth, requireRole(['dept_admin', 'admin', 'super_admin']), async (req, res) => {
  try {
    const { primaryDepartmentId, linkedDepartmentIds } = req.body;
    const issue = await Issue.findById(req.params.id);
    
    if (!issue) return res.status(404).json({ error: 'Issue not found' });

    if (primaryDepartmentId) issue.primaryDepartment = primaryDepartmentId;
    if (linkedDepartmentIds) issue.linkedDepartments = linkedDepartmentIds;
    
    await issue.save();

    const io = req.app.get('io');
    if (io) io.emit('ISSUE_REASSIGNED', { issueId: issue._id, issue });

    res.json(issue);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/issues/:id/ai-plan - Generate AI plan
router.post('/:id/ai-plan', requireAuth, requireRole(['officer', 'dept_admin', 'admin', 'super_admin']), async (req, res) => {
  try {
    const issue = await Issue.findById(req.params.id).populate('primaryDepartment');
    if (!issue) return res.status(404).json({ error: 'Issue not found' });

    const issueData = {
      title: issue.title,
      description: issue.description,
      category: issue.category,
      area: issue.area,
      urgencyScore: issue.urgencyScore,
      departmentName: issue.primaryDepartment?.name || 'Unassigned',
    };

    const aiPlan = await generateIssuePlan(issueData);
    
    issue.aiSummary = aiPlan.summary;
    issue.aiResolutionPlan = aiPlan.resolutionPlan;
    issue.aiSuggestedDepartment = aiPlan.suggestedLinkedDepartment;
    issue.aiEstimatedTime = aiPlan.estimatedTime;
    await issue.save();

    res.json({
      issue,
      suggestedLinkedDepartment: aiPlan.suggestedLinkedDepartment
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/issues/:id/ai-order - Generate professional order
router.post('/:id/ai-order', requireAuth, requireRole(['dept_admin', 'admin', 'super_admin']), async (req, res) => {
  try {
    const issue = await Issue.findById(req.params.id).populate('primaryDepartment');
    if (!issue) return res.status(404).json({ error: 'Issue not found' });

    const issueData = {
      title: issue.title,
      description: issue.description,
      area: issue.area,
      departmentName: issue.primaryDepartment?.name || 'Bhopal City Admin',
    };

    const aiOrder = await generateProfessionalOrder(issueData);
    
    issue.aiProfessionalOrder = aiOrder;
    await issue.save();

    res.json({ issue });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/issues/:id/confirm - Citizen confirms
router.post('/:id/confirm', requireAuth, async (req, res) => {
  try {
    const { isResolved, comment } = req.body;
    const issue = await Issue.findById(req.params.id);
    
    if (!issue) return res.status(404).json({ error: 'Issue not found' });

    const confirmation = await IssueConfirmation.create({
      issueId: issue._id,
      citizenId: req.user._id,
      isResolved,
      comment,
    });

    res.status(201).json(confirmation);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/issues/:id/dependency - Manually add department dependency (e.g. from AI suggestion)
router.post('/:id/dependency', requireAuth, requireRole(['officer', 'dept_admin', 'admin', 'super_admin']), async (req, res) => {
  try {
    const { dependentDepartmentId, prerequisiteDepartmentId, notes, estimatedTime } = req.body;
    const issue = await Issue.findById(req.params.id);
    if (!issue) return res.status(404).json({ error: 'Issue not found' });

    // Link in the issue document if not already linked
    if (!issue.linkedDepartments.includes(prerequisiteDepartmentId)) {
      issue.linkedDepartments.push(prerequisiteDepartmentId);
      await issue.save();
    }

    // Create the actual dependency record
    const dependency = await DepartmentDependency.create({
      issueId: issue._id,
      dependentDepartment: dependentDepartmentId,
      prerequisiteDepartment: prerequisiteDepartmentId,
      estimatedTime: estimatedTime || issue.aiEstimatedTime || null,
      notes: notes || 'Manually added via AI Plan suggestion',
    });

    res.status(201).json(dependency);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/issues/dependencies/pending - Get dependencies for the logged in department
router.get('/dependencies/pending', requireAuth, requireRole(['dept_admin', 'admin', 'super_admin']), async (req, res) => {
  try {
    if (!req.user.department) return res.json([]);
    
    const deps = await DepartmentDependency.find({
      prerequisiteDepartment: req.user.department,
      status: 'pending'
    })
    .populate('issueId')
    .populate('dependentDepartment');
    
    res.json(deps);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
